### ISSUE TITLE
Error on start npm run unit

### ISSUE THREAD

**Issue by marekkaczkowski** [eddyerburgh/jest-vue-example#1]
Looks like there is a problem getting config for jest:

```
TypeError: Cannot read property 'cacheDirectory' of undefined
    at C:\srv\jest-vue-starter\node_modules\jest\node_modules\jest-cli\build\cli\index.js:268:68
```

```
268 (0, (_jestUtil || _load_jestUtil()).createDirectory)(config.cacheDirectory);
                                                               ^68
```

Running jest aside - no problems.
Maybe babel-jest or jest-vue problem?

**Comment by eddyerburgh** [comment]
Potentially, can you try git cloning this repo, and then going into the directory and running:

```
npm install && npm run unit
```

If that still errors, can you post your system info

Thanks

**Comment by marekkaczkowski** [comment]
Partially resolved this issue with installing `jest` globally, strange 🤔.
Now I'm getting an error on components compilation:

```
C:\srv\jest-vue-starter (master) (vue-test-utils-jest-example@1.0.0)
λ jest
 FAIL  src\components\__tests__\MessageToggle.spec.js
  ● Test suite failed to run

    C:\Users\xxx\AppData\Roaming\npm\vue:2
    basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
              ^^^^^^^
    SyntaxError: missing ) after argument list

      at ScriptTransformer._transformAndBuildScript (../../Users/xxx/AppData/Roaming/npm/node_modules/jest/node_modules/jest-runtime/build/script_transformer.js:305:17)
      at Object.<anonymous> (src/components/__tests__/MessageToggle.spec.js:1:114)
          at Generator.next (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.259s
Ran all test suites.
```

**Comment by marekkaczkowski** [comment]
Looks like it was deps problem. With new versions that you pushed it works like a charm! 
Thanks Eddy :1st_place_medal:
